import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "./components/common/Header/header";
import Footer from "./components/common/Footer/Footer";
import ScrollTop from "./components/common/ScrollTop";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300','400', '500', '600','700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased w-full overflow-x-hidden`}>
        <div className="flex flex-col min-h-screen w-full">
          
          <main className="flex-grow w-full px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
          <Header />
            {children}
          </main>
          <Footer />
        </div>
        <ScrollTop />
      </body>
    </html>
  );
}